ansible:
  playbooks_dir: examples/playbooks
  cfg_file_path: examples/ansible.cfg
  playbook_cmd: /usr/bin/ansible-playbook

routing_keys:
    - org.fedoraproject.prod.ansible.playbook.start
    - org.fedoraproject.prod.buildsys.build.state.change

plugins:
  looper:
    name: fedmsg
  translater:
    name: rkname
