ansible:
  playbooks_dir: examples/playbooks
  cfg_file_path: examples/ansible.cfg
  playbook_cmd: /usr/bin/ansible-playbook

routing_keys:
    - org.fedoraproject.dev.logger.hello_world

plugin: fedmsg
path_translator: rkdirectory
